name: Turisten
safe: true
lsi: false
baseurl: /turisten
exclude: [node_modules, README.md]
permalink: /:year/:month/:title
timezone: Europe/Stockholm
paginate: 15

# Authors
authors:
  gustaf:
    name: Gustaf
    avatar: avatar-gustaf.png
  linn:
    name: Linn
    avatar: avatar-linn.png
